// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ProxyWallet$Type } from "./ProxyWallet";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProxyWallet"]: ProxyWallet$Type;
    ["contracts/ProxyWallet.sol:ProxyWallet"]: ProxyWallet$Type;
  }

  interface ContractTypesMap {
    ["ProxyWallet"]: GetContractReturnType<ProxyWallet$Type["abi"]>;
    ["contracts/ProxyWallet.sol:ProxyWallet"]: GetContractReturnType<ProxyWallet$Type["abi"]>;
  }
}
